M48
; DRILL file {KiCad 7.0.9-1.fc39} date Mon 27 Nov 2023 01:07:50 AM -03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-27T01:07:50-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-1.fc39
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1969
%
G90
G05
T1
X4.5232Y-1.2268
X4.5331Y-2.6992
X6.4Y-1.2469
X6.4055Y-2.2705
T0
M30
